### ISSUE TITLE
this.afa.createUserWithEmailAndPassword is not a function

### ISSUE THREAD

**Issue by Rofer11607** [AnthonyNahas/ngx-auth-firebaseui#578]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

macOS catalina 10.15.6

### Versions

{
	"name": "partner-data-entry",
	"version": "0.0.0",
	"main": "dist/out-tsc/src/AppMain.js",
	"scripts": {
		"ng": "ng",
		"start": "ng serve",
		"build": "ng build",
		"test": "ng test",
		"lint": "ng lint",
		"e2e": "ng e2e",
		"serve": "ng build --prod && tsc-silent -p tsconfig.json --suppress @ && electron ."
	},
	"private": true,
	"dependencies": {
		"@angular-material-extensions/password-strength": "^4.1.2",
		"@angular/animations": "~8.2.14",
		"@angular/cdk": "^8.2.3",
		"@angular/common": "~8.2.14",
		"@angular/compiler": "~8.2.14",
		"@angular/core": "~8.2.14",
		"@angular/fire": "^5.4.2",
		"@angular/flex-layout": "^8.0.0-beta.27",
		"@angular/forms": "~8.2.14",
		"@angular/material": "^8.2.3",
		"@angular/platform-browser": "~8.2.14",
		"@angular/platform-browser-dynamic": "~8.2.14",
		"@angular/router": "~8.2.14",
		"@ngx-formly/bootstrap": "^5.0.0",
		"@ngx-formly/core": "^5.0.0",
		"@ngx-formly/schematics": "^5.9.3",
		"@teamhive/lottie-player": "^1.0.0",
		"@types/googlemaps": "^3.39.13",
		"bootstrap": "^4.5.2",
		"electron": "^10.0.0",
		"firebase": "^7.19.1",
		"ngx-auth-firebaseui": "^4.4.0",
		"ngx-google-places-autocomplete": "^2.0.4",
		"ngx-mask": "^10.0.1",
		"rxjs": "~6.4.0",
		"tsc-silent": "^1.2.1",
		"tslib": "^2.0.1",
		"zone.js": "~0.9.1"
	},
	"devDependencies": {
		"@angular-devkit/architect": "<0.900 || ^0.900.0-0 || ^9.0.0-0",
		"@angular-devkit/build-angular": "~0.803.24",
		"@angular/cli": "~8.3.24",
		"@angular/compiler-cli": "~8.2.14",
		"@angular/language-service": "~8.2.14",
		"@types/jasmine": "~3.3.8",
		"@types/jasminewd2": "~2.0.3",
		"@types/node": "~8.9.4",
		"codelyzer": "^5.0.0",
		"firebase-tools": "^7.12.0",
		"fuzzy": "^0.1.3",
		"inquirer": "^6.2.2",
		"inquirer-autocomplete-prompt": "^1.0.1",
		"jasmine-core": "~3.4.0",
		"jasmine-spec-reporter": "~4.2.1",
		"karma": "~4.1.0",
		"karma-chrome-launcher": "~2.2.0",
		"karma-coverage-istanbul-reporter": "~2.0.1",
		"karma-jasmine": "~2.0.1",
		"karma-jasmine-html-reporter": "^1.4.0",
		"protractor": "~5.4.0",
		"ts-node": "~7.0.0",
		"tslint": "~5.15.0",
		"typescript": "~3.5.3"
	}
}

### Repro steps

1) Follow the installation instructions,
**I had great difficulty installing this, steps to fix issues i found on the way:
   2.1) downgrade @anuglar/flex-layout package to 8.0.0beta.27
   2.2) install tslib
3) use the ngx-auth-firebaseui component
4) try to register as a user using email.

### The log given by the failure

TypeError: this.afa.createUserWithEmailAndPassword is not a function
    at AuthProcessService.<anonymous> (http://localhost:4200/vendor.js:200592:55)
    at Generator.next (<anonymous>)
    at http://localhost:4200/vendor.js:202381:71
    at new ZoneAwarePromise (http://localhost:4200/polyfills.js:4241:29)
    at __awaiter (http://localhost:4200/vendor.js:202377:12)
    at AuthProcessService.signUp (http://localhost:4200/vendor.js:200590:71)
    at AuthComponent.<anonymous> (http://localhost:4200/vendor.js:201129:47)
    at Generator.next (<anonymous>)
    at http://localhost:4200/vendor.js:202381:71

the application throws this error upon completion of the register with email form: this.afa.createUserWithEmailAndPassword is not a function

### Desired functionality

I am trying to register a user using email

**Comment by Rofer11607** [comment]
Never mind I forgot to initialize angular/fire
