### ISSUE TITLE
SSR/Server – Error message with material icons.

### ISSUE THREAD

**Issue by JanOschii** [AnthonyNahas/ngx-auth-firebaseui#582]
### Bug Report 
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

Firebase Functions / SSR

### Versions (Local)
```
Angular CLI: 9.1.12
Node: 10.16.3
OS: win32 x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms    
... language-service, platform-browser, platform-browser-dynamic    
... platform-server, router
Ivy Workspace: Yes

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.901.12
@angular-devkit/build-angular              0.901.12
@angular-devkit/build-ng-packagr           0.901.12
@angular-devkit/build-optimizer            0.901.12
@angular-devkit/build-webpack              0.901.12
@angular-devkit/core                       10.1.3
@angular-devkit/schematics                 10.1.3
@angular/cdk                               9.2.4
@angular/fire                              6.0.3
@angular/flex-layout                       9.0.0-beta.31
@angular/material                          9.2.4
@angular/pwa                               0.1001.3
@angular/service-worker                    10.1.3
@ngtools/webpack                           9.1.12
@nguniversal/builders                      9.1.1
@nguniversal/common                        9.1.1
@nguniversal/express-engine                9.1.1
@nguniversal/module-map-ngfactory-loader   8.2.6
@schematics/angular                        10.1.3
@schematics/update                         0.901.12
ng-packagr                                 9.1.5
rxjs                                       6.5.5
typescript                                 3.7.5
webpack                                    4.42.0
```

### Repro steps
Using `ngx-auth-firebaseui` with ssr in firebase function.

### The log given by the failure
```
ERROR Error: Error retrieving icon :google-colored! 
    at Subscriber_SafeSubscriber._currentIconFetch._iconRegistry.getNamedSvgIcon.pipe.subscribe [as _error] (/srv/dist/server/main.js:170586:56)
    at Subscriber_SafeSubscriber.__tryOrUnsub (/srv/dist/server/main.js:62400:16)
    at Subscriber_SafeSubscriber.error (/srv/dist/server/main.js:62352:26)
    at Subscriber_Subscriber._error (/srv/dist/server/main.js:62292:26)
    at Subscriber_Subscriber.error (/srv/dist/server/main.js:62272:18)
    at take_TakeSubscriber._error (/srv/dist/server/main.js:62292:26)
    at take_TakeSubscriber.error (/srv/dist/server/main.js:62272:18)
    at map_MapSubscriber._error (/srv/dist/server/main.js:62292:26)
    at map_MapSubscriber.error (/srv/dist/server/main.js:62272:18)
    at tap_TapSubscriber._error (/srv/dist/server/main.js:114070:26) 
ERROR Error: Error retrieving icon :apple! ...
ERROR Error: Error retrieving icon :facebook! ...
ERROR Error: Error retrieving icon :twitter! ...
ERROR Error: Error retrieving icon :github! ...
ERROR Error: Error retrieving icon :microsoft! ...
ERROR Error: Error retrieving icon :yahoo! ...
```

### Desired functionality
No error messages. Icons are not required for server-side rendering.

### Workaround 
I have found a way to solve this by defining the icons with a short svg string in the AppComponent.
As far as i understand, there should not be any need for an icon while server side rendering.
@dabbid gave the right impulse: [See here.](https://github.com/angular/components/issues/9728#issuecomment-698897020)
```
import { isPlatformServer } from '@angular/common';
import { Component, Inject, PLATFORM_ID } from '@angular/core';
import { MatIconRegistry } from '@angular/material/icon';
import { DomSanitizer } from '@angular/platform-browser';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {

  constructor(
    private matIconRegistry: MatIconRegistry,
    private domSanitizer: DomSanitizer,
    @Inject(PLATFORM_ID) private platformId: string ) {

      const svg = '<svg viewBox="0 0 20 20" width="20" height="20" xmlns="http://www.w3.org/2000/svg"></svg>'

      if( isPlatformServer(this.platformId) ) {
        this.matIconRegistry.addSvgIconLiteral( 'google'         , this.domSanitizer.bypassSecurityTrustHtml(svg) )
        this.matIconRegistry.addSvgIconLiteral( 'apple'          , this.domSanitizer.bypassSecurityTrustHtml(svg) )
        this.matIconRegistry.addSvgIconLiteral( 'google-colored' , this.domSanitizer.bypassSecurityTrustHtml(svg) )
        this.matIconRegistry.addSvgIconLiteral( 'facebook'       , this.domSanitizer.bypassSecurityTrustHtml(svg) )
        this.matIconRegistry.addSvgIconLiteral( 'twitter'        , this.domSanitizer.bypassSecurityTrustHtml(svg) )
        this.matIconRegistry.addSvgIconLiteral( 'github'         , this.domSanitizer.bypassSecurityTrustHtml(svg) )
        this.matIconRegistry.addSvgIconLiteral( 'microsoft'      , this.domSanitizer.bypassSecurityTrustHtml(svg) )
        this.matIconRegistry.addSvgIconLiteral( 'yahoo'          , this.domSanitizer.bypassSecurityTrustHtml(svg) )
        this.matIconRegistry.addSvgIconLiteral( 'phone'          , this.domSanitizer.bypassSecurityTrustHtml(svg) )
      }
  }

}


```

**Comment by AnthonyNahas** [comment]
@JanOschii thanks for opening this ticket.

Can you please provide an appropriate PR for that <3 ?

**Comment by leibovitzgil** [comment]
this bug has to do with the way the path on the package.json assets was defined.
to fix this issue, i've set it this way:
{
                "glob": "**/*",
                "input": "./node_modules/ngx-auth-firebaseui/assets/",
                "output": "/assets/"
 }


instead of the original setup which was defined on [npmjs](https://www.npmjs.com/package/ngx-auth-firebaseui/v/1.0.0) :
{
          "glob": "**/*",
          "input": "../node_modules/ngx-auth-firebaseui/dist/assets/",
          "output": "./assets/"
}
